export const data = [
  {
    date: "2018-10-17",
    startTime: "07:00",
    endTime: "06:00",
    hrs: "7.4",
    labourType: "Project",
    project: "123lac",
    phase: "development",
    indirectCode: "SPEC",
    comment: "testing",
    overTime: "false",
    lunchTaken: "false",
    operation: "manager",
    qty: 0,
    resource: "Andrew Mills",
    expenseCode: "INDIRECT LABOR",
    jcdept: "OPS-OPERATION",
  },
  {
    date: "2023-5-3",
    startTime: "07:00",
    endTime: "06:00",
    hrs: "7.4",
    labourType: "Project",
    project: "123lac",
    phase: "development",
    indirectCode: "SPEC",
    comment: "testing",
    overTime: "false",
    lunchTaken: "false",
    operation: "manager",
    qty: 0,
    resource: "Andrew Mills",
    expenseCode: "INDIRECT LABOR",
    jcdept: "OPS-OPERATION",
  },
  {
    date: "2022-8-23",
    startTime: "07:00",
    endTime: "06:00",
    hrs: "7.4",
    labourType: "Project",
    project: "123lac",
    phase: "development",
    indirectCode: "SPEC",
    comment: "testing",
    overTime: "false",
    lunchTaken: "false",
    operation: "manager",
    qty: 0,
    resource: "Andrew Mills",
    expenseCode: "INDIRECT LABOR",
    jcdept: "OPS-OPERATION",
  },
];
export const weekData = [
  {
    hours: "Production Hours",
  },
  {
    hours: "Indirect Hours",
  },
  {
    hours: "Total Hours",
  },
];
